### ISSUE TITLE
[Feature Request] 数値IDで投稿を取得したい

### ISSUE THREAD

**Issue by otofune** [kibela/kibela-api-v1-document#19]
こんにちは。
`https://example.kibe.la/@example/1` の投稿を取得するのにランダムな Relay ID でなく `1` で取得できるようにならないでしょうか。

---

Slack で Kibela のリンクを unfurl する bot を作成しようとしていたのですが、次のようなクエリが動作しないことに気がつきました。

```gql
query {
    note(id: 1) {
        author {
            id
            account
            avatarImage {
                url
            }
        }
        title
        url
        publishedAt
    }
}
```
```json
{
  "data": {
    "note": null
  },
  "errors": [
    {
      "message": "The relay ID is invalid",
      "locations": [
        {
          "line": 2,
          "column": 5
        }
      ],
      "path": [
        "note"
      ],
      "extensions": {
        "code": "INVALID_ID",
        "id": "1"
      }
    }
  ]
}
```

> The ID scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; **however, it is not intended to be human-readable. When expected as an input type, any string (such as "4") or integer (such as 4) input value will be accepted as an ID.**

上記の太字部分がどういった意図なのかがあまりわかっておりませんが、現状では動作しないということでリクエストさせて頂きました。

**Comment by gfx** [comment]
こんにちは！はい、ご要望についてはよくわかりますので、何らかの形で対応しようと思います。

この要望は、数値のIDというよりはURL（パス）を直接Web APIに与えたいという趣旨でよいでしょうか。つまり、 `/notes/42` （またはURLをそのまま）を扱えれば十分かと思いますが、いかがですか。

**Comment by otofune** [comment]
その通りです、パスでもURLでも良いと思います。

---
返信が遅れました、ありがとうございます!
UI にも URL に表出していないランダムなキーでしか単体の投稿が取得できないことがつらいことが私が報告したモチベーションで、数値ID/パス/URL で投稿を取得できれば嬉しいです。

**Comment by gfx** [comment]
おまたせしました。こちら `Query.noteFromPath(path: String!): Note!` を追加したので確認いただけますでしょうか。

**Comment by otofune** [comment]
無事使え、目的のbotが完成しました。ありがとうございました

**Comment by gfx** [comment]
よかったです！🤗

**Comment by gfx** [comment]
FYI: 画像 (添付ファイル, attachment) は `Query.attachmentFromPath` で取得できるようになりました。

https://github.com/kibela/kibela-api-v1-document/pull/22


（以前から `attachmentByPath` はありましたが、名前が適当でないので `attachmentFromPath` にしたのが今日です）
