### ISSUE TITLE
[Feature Request] publish .gqlschema

### ISSUE THREAD

**Issue by fumito-ito** [kibela/kibela-api-v1-document#2]
Easy to use from client, please publish current GraphQL scheme as `.gqlschema`. This format is standard to open api schema e.g. [SnapChat](https://github.com/Snapchat/storykit), [GitHub](https://developer.github.com/v4/)

**Comment by gfx** [comment]
Thanks for the request.

You can already get the GraphQL schema via [Introspection API](https://graphql.org/learn/introspection/), but will consider to publish it to make it easy.

**Comment by gfx** [comment]
Now schema.graphql is added and will be automatically synchronized to the service, like https://github.com/kibela/kibela-api-v1-document/pull/4
