### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by typester** [kibela/kibela-api-v1-document#3]
Hi, kibe.la api team,

I tried to create a PWA application to test or to evaluate your APIs.
But I found that this api seemed not to support CORS at this time.

Do you have any plan to support CORS?
I'm very happy if you will :)

**Comment by gfx** [comment]
We have a plan to support CORS soon, of course!

**Comment by gfx** [comment]
CORS works now!

Here is a working example with the `fetch` API:

https://github.com/kibela/hello-kibela.ts/blob/1abf27e91cf2801571706c27f97e59596d02b097/index.html#L43-L54
