### ISSUE TITLE
[Feature Request] customEmoji

### ISSUE THREAD

**Issue by kounoike** [kibela/kibela-api-v1-document#48]
## 要望

`customEmojiFromCode(code: String!)` のようなカスタム絵文字をコードから検索する機能が欲しい。

## 背景

SlackとKibelaでカスタム絵文字を同期するツールを作成しています。 https://github.com/kounoike/slack-to-kibela-emoji-syncer
最初の同期とSlackでの絵文字追加時のKibelaへの追加は出来たのですが、Slackから絵文字を削除したときにKibelaから削除する処理が、今のままだと絵文字全検索することになり煩雑となってしまいます（deleteCustomEmojiはcodeでなくIDを取るため）。

**Comment by pocke** [comment]
Issue作成ありがとうございます。
こちらあると良さそうなAPIだと思うため、前向きに実装を検討させていただきます。

**Comment by kounoike** [comment]
ありがとうございます。よろしくお願いします。
考えてみたら `deleteEmojiFromCode(code: String!)` でもいいですね。どちらがいいかはお任せします。

**Comment by pocke** [comment]
遅くなりました。 `query.customEmojiFromCode`を追加しました。このクエリで絵文字のコードからカスタム絵文字を取得できます。

ref: https://github.com/kibela/kibela-api-v1-document/pull/52
