### ISSUE TITLE
"noteBrowsingHistries" is misspelled?

### ISSUE THREAD

**Issue by nekoya** [kibela/kibela-api-v1-document#53]
Hi, team. I have a question about the schema.

https://github.com/kibela/kibela-api-v1-document/blob/ac8d11adfe132d26d8f3b79d098fc98b390daf9e/schema.graphql#L2729

Does `noteBrowsingHistries` intend "Histories"?

**Comment by pocke** [comment]
Thank you for reporting the issue!

Ah, you are correct. It is a typo. We will rename the query to `noteBrowsingHistories`.
It can be a breaking change, so we will keep the old name for a while.


Thanks!

**Comment by pocke** [comment]
We have released kibela with the new query, which is `noteBrowsingHistories`. It is the same as `noteBrowsingHistries` but without the typo. `noteBrowsingHistries` has been deprecated.

You can find the diff from here https://github.com/kibela/kibela-api-v1-document/pull/54.


Thanks for reporting!
