### ISSUE TITLE
UploadAttachmentInputのdataの型が実際にはBufferではないか

### ISSUE THREAD

**Issue by kawaharasatoru-mf** [kibela/kibela-api-v1-document#63]
こんにちは。ドキュメントと実際の仕様について確認させてほしいです 🙇🏼 

Webコンソールでのドキュメントでは、 `UploadAttachmentInput` の dataについて
`data: Blob!`
と記載がありますが、実際には `Buffer` 型ではないでしょうか？

msgpackを利用して画像をアップロードしたく、
uploadAttachmentを利用したかったのですが、
画像をBlobに変換してから送信すると、以下のようなエラーレスポンスが返ってきました。

```
{
  errors: [
    {
      message: 'Unexpected error occurred. Please contact us to solve this problem.',
      extensions: { code: 'UNEXPECTED_FAILURE' }
    }
  ]
}
```

この際のquery, variableは以下です。

```
{
  query: 'mutation UploadAttachment($attachmentInput: UploadAttachmentInput!) {\n' +
    '  uploadAttachment(input: $attachmentInput) {\n' +
    '    attachment {\n' +
    '      id\n' +
    '      key\n' +
    '      name\n' +
    '      path\n' +
    '      url\n' +
    '    }\n' +
    '  }\n' +
    '}',
  variables: {
    attachmentInput: {
      name: 'hogehoge.png',
      data: Blob {
        [Symbol(kHandle)]: Blob {},
        [Symbol(kLength)]: 45746,
        [Symbol(kType)]: 'image/png'
      },
      kind: 'GENERAL'
    }
  }
}
```

その後、
https://github.com/kibela/kibela-to-kibela/blob/master/kibela-import.ts#L178
こちらのkibela-to-kibelaのプロジェクトでは、dataにBufferを入れているのを確認し、
Buffer型で送信してみたところエラーが無くなり、画像のアップロードも正常に終了しました。

ご確認いただけると嬉しいです。

**Comment by shimbaco** [comment]
@kawaharasatoru-mf 
確認が遅くなり申し訳ありません！(そしてお久しぶりです！)

勘違いでしたら申し訳ないのですが、おそらく[JavaScriptのAPIにおけるBlob](https://developer.mozilla.org/ja/docs/Web/API/Blob)とWebコンソールから参照できるドキュメントに記載されているBlob (GraphQL APIにおけるBlob型) を混同されているのかな？と思いました。
GraphQL APIのBlob型は画像等のデータを送る型としてKibela側で定義した名前で、JavaScript APIのBlobと同じものではありません。

JavaScriptで `data` を送る場合は、仰るとおりBuffer型で送信する必要があります。

ドキュメントの情報が足りないことで混乱させてしまい申し訳ありません！
今後ドキュメントをよりわかりやすくしていけたらと思います 🙏

**Comment by kawaharasatoru-mf** [comment]
@shimbaco お返事ありがとうございます。そしてお久しぶりです！

> 混同されているのかな？と思いました。

なるほど。勘違いを理解しました。

すっかり頭の中でJavaScriptの文脈で理解しようとしていたのと、
また、今回、 [GraphQL Code Generator](https://www.the-guild.dev/graphql/codegen) を使って型ファイルを生成していたのですが、開発環境上で `Scalar['Blob']` と補完表示されていたため（表示のみで実際にはanyで解釈されるのですが）、すっかり勘違いしておりました 🙇🏼 

お返事いただいたことで疑問は完全に解消しましたのでクローズさせてもらいます。
お騒がせいたしました。

これからもよろしくお願いします！

**Comment by shimbaco** [comment]
ご確認ありがとうございます！
なるほどそういった背景があったんですね。ドキュメント改善の参考にします。

今後ともよろしくお願いします！🙏
